### ISSUE TITLE
Allow JS plugins/modules to be loaded from subfolders

### ISSUE THREAD

**Issue by XeduR** [coronalabs/submodule-platform-emscripten#2]
Currently, JavaScript files can only be loaded from the project's root directory.

For convenience, as well as for organising files for HTML5 projects, it'd be a great if JS files could be placed inside subfolders as well.

**Comment by Shchvova** [comment]
This code should be altered to fix it.
https://github.com/coronalabs/submodule-platform-emscripten/blob/a9fbd098fb4bc2f85b4c61f324f43909b8cb1365/Rtt_EmscriptenJSPluginLoader.cpp#L350-L362
Instead of just bailing on the first failed attempt (and replacing all dots with underscores) try iterating through directory structure, replacing dots with slashes, then all underscores.
Or, preferably, just replace all dots with slashes, then if no file found, all slashes with underscores. Seems like an easy fix.
